# Generated by Django 5.2.1 on 2025-05-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Китай', max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamingMouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('optical', 'Оптичний'), ('laser', 'Лазерний')], default='optical', max_length=50)),
                ('dpi', models.PositiveIntegerField(default=800)),
                ('weight', models.PositiveIntegerField(help_text='В грамах')),
                ('color', models.CharField(default='Чорний', max_length=50)),
                ('is_wireless', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_quantity', models.PositiveIntegerField(default=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.brand')),
            ],
        ),
    ]
